version: "3"

services:
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes: 
      - ./db/data/:/app
      - ./db/mysqldata:/var/lib/mysql
    networks: 
      - cookbook

  app:
    container_name: app
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    volumes: 
      - ./src/:/var/www/html/
    networks: 
      - cookbook

  web:
    container_name: web
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
        - ./src/:/var/www/html
        - ./nginx/nginx_local_template.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "8087:80"
    depends_on:
      - db
      - app
    networks:
      - cookbook

volumes:
    mysqldata:
networks: 
  cookbook:
    driver: bridge