version: "3"
# volumes:
#   mysql_data:

services: 
  app:
    build:
      context: ./dockerbuild
      dockerfile: Dockerfile
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on: 
      - "app"
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./dockerbuild/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  # db:
  #   image: mysql:5.7
  #   volumes: 
  #     - mysql_data:/var/lib/mysql